import type { ApiUser, Cosigner, PolicyRule, SignRequest, WorkspaceSettings } from "@/lib/types";

const minutesAgo = (minutes: number, now: number) =>
  new Date(now - minutes * 60_000).toISOString();

export const DEFAULT_SETTINGS: WorkspaceSettings = {
  workspaceName: "Northstar Production",
  callbackAuth: "json",
  operatorName: "ops@northstar",
};

export const DEFAULT_POLICY: PolicyRule[] = [
  {
    id: "block-ota",
    name: "Block one-time addresses",
    description:
      "Reject transfers to one-time addresses unless they are first allowlisted as an unmanaged wallet.",
    priority: 10,
    enabled: true,
    match: { kinds: ["tx_sign", "tx_approval"], dstTypes: ["ONE_TIME"], dstAddressTypes: ["ONE_TIME"] },
    decision: "REJECT",
    designatedSigner: "api_signer_treasury",
  },
  {
    id: "block-ota-enable",
    name: "Block enabling one-time addresses",
    description:
      "Configuration requests that enable one-time address withdrawals require a separate change-control ticket and are rejected here.",
    priority: 15,
    enabled: true,
    match: {
      kinds: ["config_change"],
      configTypes: ["ENABLE_ONE_TIME_ADDRESS"],
    },
    decision: "REJECT",
    designatedSigner: "api_approver_ops",
  },
  {
    id: "auto-internal",
    name: "Auto-sign internal vault transfers under $25k",
    description:
      "Treasury rebalances between named vaults at or below $25,000 USD are signed automatically.",
    priority: 20,
    enabled: true,
    match: {
      kinds: ["tx_sign"],
      operations: ["TRANSFER"],
      srcTypes: ["VAULT"],
      dstTypes: ["VAULT"],
      maxUsd: 25_000,
    },
    decision: "APPROVE",
    designatedSigner: "api_signer_treasury",
  },
  {
    id: "auto-whitelist",
    name: "Auto-sign allowlisted destinations under $100k",
    description:
      "Transfers to allowlisted exchanges, network connections, and unmanaged wallets at or below $100,000 USD are signed automatically.",
    priority: 30,
    enabled: true,
    match: {
      kinds: ["tx_sign"],
      operations: ["TRANSFER"],
      srcTypes: ["VAULT"],
      dstTypes: ["EXCHANGE", "UNMANAGED", "NETWORK_CONNECTION"],
      dstAddressTypes: ["WHITELISTED"],
      maxUsd: 100_000,
    },
    decision: "APPROVE",
    designatedSigner: "api_signer_treasury",
  },
  {
    id: "review-web3",
    name: "Hold contract calls and typed messages",
    description:
      "Any CONTRACT_CALL, TYPED_MESSAGE, or RAW signing request is held for an operator even when the destination is allowlisted.",
    priority: 40,
    enabled: true,
    match: {
      kinds: ["tx_sign", "tx_approval"],
      operations: ["CONTRACT_CALL", "TYPED_MESSAGE", "RAW"],
    },
    decision: "REVIEW",
    designatedSigner: "api_signer_treasury",
  },
  {
    id: "review-config",
    name: "Hold workspace configuration changes",
    description:
      "Policy edits, users, quorum, and network connections wait for an operator on the callback handler.",
    priority: 50,
    enabled: true,
    match: { kinds: ["config_change"] },
    decision: "REVIEW",
    designatedSigner: "api_approver_ops",
  },
  {
    id: "review-large",
    name: "Hold transfers above policy thresholds",
    description:
      "Anything that did not match an auto-sign rule is held so an operator can co-sign or reject it.",
    priority: 90,
    enabled: true,
    match: { kinds: ["tx_sign", "tx_approval"] },
    decision: "REVIEW",
    designatedSigner: "api_signer_treasury",
  },
];

function whitelistProposal(maxUsd: number) {
  const current = structuredClone(
    DEFAULT_POLICY.find((rule) => rule.id === "auto-whitelist")!,
  );
  const proposed = structuredClone(current);
  proposed.match.maxUsd = maxUsd;
  return { ruleId: current.id, current, proposed };
}

export function defaultApiUsers(): ApiUser[] {
  return [
    {
      id: "api_signer_treasury",
      displayName: "treasury-bot",
      role: "Signer",
      pairedCosignerId: "cosigner-nitro-prod-1",
      callbackEnabled: true,
    },
    {
      id: "api_approver_ops",
      displayName: "ops-approver-bot",
      role: "Approver",
      pairedCosignerId: "cosigner-sgx-dr-1",
      callbackEnabled: true,
    },
    {
      id: "api_signer_lab",
      displayName: "lab-bot",
      role: "Signer",
      pairedCosignerId: "cosigner-gcp-lab-1",
      callbackEnabled: false,
    },
  ];
}

export function defaultCosigners(now: number): Cosigner[] {
  return [
    {
      id: "cosigner-nitro-prod-1",
      name: "nitro-prod-1",
      enclave: "AWS_NITRO",
      region: "us-east-1",
      status: "online",
      pairedApiUser: "api_signer_treasury",
      role: "Signer",
      callbackConfigured: true,
      lastHeartbeatAt: minutesAgo(0.2, now),
      signed24h: 148,
    },
    {
      id: "cosigner-sgx-dr-1",
      name: "sgx-dr-1",
      enclave: "INTEL_SGX",
      region: "eu-west-1",
      status: "online",
      pairedApiUser: "api_approver_ops",
      role: "Approver",
      callbackConfigured: true,
      lastHeartbeatAt: minutesAgo(0.4, now),
      signed24h: 36,
    },
    {
      id: "cosigner-gcp-lab-1",
      name: "gcp-lab-1",
      enclave: "GCP_CONFIDENTIAL_SPACE",
      region: "us-central1",
      status: "degraded",
      pairedApiUser: "api_signer_lab",
      role: "Signer",
      callbackConfigured: false,
      lastHeartbeatAt: minutesAgo(18, now),
      signed24h: 0,
    },
  ];
}

export function defaultRequests(now: number): SignRequest[] {
  return [
    {
      id: "req_7f3c91a2",
      txId: "fb_tx_9c21e0",
      externalTxId: "northstar-wd-4412",
      kind: "tx_sign",
      status: "auto_approved",
      createdAt: minutesAgo(4, now),
      decidedAt: minutesAgo(4, now),
      slaDeadlineAt: new Date(now + 18_000).toISOString(),
      retryCount: 2,
      operation: "TRANSFER",
      assetId: "ETH",
      amount: "250",
      amountUsd: 825_000,
      sourceName: "Treasury Hot",
      sourceId: "0",
      sourceType: "VAULT",
      destName: "Coinbase Prime",
      destId: "coinbase_prime",
      destType: "EXCHANGE",
      destAddress: "0x4b1c0e8d9a77c3f2e91a0b6d4c8f12aa90e31b77",
      destAddressType: "WHITELISTED",
      note: "Weekly CEX top-up for market making",
      fee: "0.0021 ETH",
      signerId: "api_signer_treasury",
      cosignerId: "cosigner-nitro-prod-1",
      matchedRuleName: "Fireblocks TAP",
      policyVerdict: "APPROVE",
      decisionSource: "policy",
      rawPayload: {},
    },
    {
      id: "req_b18e44d0",
      txId: "fb_tx_11ab90",
      externalTxId: "otc-fill-882",
      kind: "tx_sign",
      status: "auto_approved",
      createdAt: minutesAgo(11, now),
      decidedAt: minutesAgo(11, now),
      slaDeadlineAt: new Date(now + 9_000).toISOString(),
      retryCount: 5,
      operation: "TRANSFER",
      assetId: "USDC",
      amount: "2000000",
      amountUsd: 2_000_000,
      sourceName: "Treasury Hot",
      sourceId: "0",
      sourceType: "VAULT",
      destName: "OTC Desk",
      destId: "7",
      destType: "VAULT",
      destAddress: "0x91aa20c4d0e0b11c4e8f77a1c0d4b9e2aa441900",
      destAddressType: "WHITELISTED",
      note: "Settle Blockfills RFQ 882",
      fee: "12.4 USDC",
      signerId: "api_signer_treasury",
      cosignerId: "cosigner-nitro-prod-1",
      matchedRuleName: "Fireblocks TAP",
      policyVerdict: "APPROVE",
      decisionSource: "policy",
      rawPayload: {},
    },
    {
      id: "req_e90c12aa",
      txId: "fb_tx_c4d901",
      kind: "tx_sign",
      status: "auto_approved",
      createdAt: minutesAgo(16, now),
      decidedAt: minutesAgo(16, now),
      slaDeadlineAt: new Date(now + 21_000).toISOString(),
      retryCount: 3,
      operation: "CONTRACT_CALL",
      assetId: "ETH",
      amount: "40",
      amountUsd: 132_000,
      sourceName: "Yield Ops",
      sourceId: "3",
      sourceType: "VAULT",
      destName: "Uniswap V3 Router",
      destId: "uniswap_v3",
      destType: "UNMANAGED",
      destAddress: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
      destAddressType: "WHITELISTED",
      note: "exactInputSingle WETH → USDC",
      fee: "0.0044 ETH",
      signerId: "api_signer_treasury",
      cosignerId: "cosigner-nitro-prod-1",
      matchedRuleName: "Fireblocks TAP",
      policyVerdict: "APPROVE",
      decisionSource: "policy",
      rawPayload: {},
    },
    {
      id: "req_cfg_441",
      kind: "config_change",
      status: "auto_approved",
      createdAt: minutesAgo(28, now),
      decidedAt: minutesAgo(28, now),
      slaDeadlineAt: new Date(now + 12_000).toISOString(),
      retryCount: 8,
      configType: "POLICY_APPROVAL",
      extraInfo: {
        summary: "Raise Coinbase Prime auto-sign ceiling from $100k to $250k",
        submittedBy: "treasury-lead@northstar",
        ...whitelistProposal(250_000),
      },
      signerId: "api_approver_ops",
      cosignerId: "cosigner-sgx-dr-1",
      matchedRuleName: "Fireblocks TAP",
      policyVerdict: "APPROVE",
      decisionSource: "policy",
      rawPayload: {},
    },
    {
      id: "req_a11c0038",
      txId: "fb_tx_55ee21",
      externalTxId: "rebalance-gas-0915",
      kind: "tx_sign",
      status: "auto_approved",
      createdAt: minutesAgo(42, now),
      decidedAt: minutesAgo(42, now),
      slaDeadlineAt: minutesAgo(41.5, now),
      retryCount: 0,
      operation: "TRANSFER",
      assetId: "ETH",
      amount: "2.5",
      amountUsd: 8_250,
      sourceName: "Treasury Hot",
      sourceId: "0",
      sourceType: "VAULT",
      destName: "Gas Station",
      destId: "12",
      destType: "VAULT",
      destAddress: "0x22b90e1c44aa9011d0ee4c8f12aa90e31b77001a",
      destAddressType: "WHITELISTED",
      note: "Refill gas station",
      fee: "0.0008 ETH",
      signerId: "api_signer_treasury",
      cosignerId: "cosigner-nitro-prod-1",
      matchedRuleId: "auto-internal",
      matchedRuleName: "Auto-sign internal vault transfers under $25k",
      policyVerdict: "APPROVE",
      decisionSource: "policy",
      rawPayload: {},
    },
    {
      id: "req_d77b2109",
      txId: "fb_tx_08cc19",
      kind: "tx_sign",
      status: "auto_rejected",
      createdAt: minutesAgo(55, now),
      decidedAt: minutesAgo(55, now),
      slaDeadlineAt: minutesAgo(54.5, now),
      retryCount: 0,
      operation: "TRANSFER",
      assetId: "ETH",
      amount: "12",
      amountUsd: 39_600,
      sourceName: "Treasury Hot",
      sourceId: "0",
      sourceType: "VAULT",
      destName: "Unknown address",
      destType: "ONE_TIME",
      destAddress: "0x9f3a11c0deadbeefc0ffee112233445566778899",
      destAddressType: "ONE_TIME",
      note: "Vendor payout — not allowlisted",
      fee: "0.0015 ETH",
      signerId: "api_signer_treasury",
      cosignerId: "cosigner-nitro-prod-1",
      matchedRuleId: "block-ota",
      matchedRuleName: "Block one-time addresses",
      policyVerdict: "REJECT",
      decisionSource: "policy",
      rejectionReason: "Destination is a one-time address",
      rawPayload: {},
    },
    {
      id: "req_c02f8811",
      txId: "fb_tx_77aa03",
      kind: "tx_sign",
      status: "approved",
      createdAt: minutesAgo(110, now),
      decidedAt: minutesAgo(108, now),
      slaDeadlineAt: minutesAgo(109.5, now),
      retryCount: 1,
      operation: "STAKE",
      assetId: "SOL",
      amount: "15000",
      amountUsd: 2_175_000,
      sourceName: "Yield Ops",
      sourceId: "3",
      sourceType: "VAULT",
      destName: "Jito validator",
      destType: "UNMANAGED",
      destAddress: "Jito4APyf642JPZWqKq9JNqXqXqJitoStake111111",
      destAddressType: "WHITELISTED",
      note: "Increase Jito stake",
      signerId: "api_signer_treasury",
      cosignerId: "cosigner-nitro-prod-1",
      matchedRuleId: "review-large",
      matchedRuleName: "Hold transfers above policy thresholds",
      policyVerdict: "REVIEW",
      decisionSource: "operator",
      operator: "ops@northstar",
      rawPayload: {},
    },
    {
      id: "req_91aa2204",
      txId: "fb_tx_btc019",
      kind: "tx_sign",
      status: "auto_approved",
      createdAt: minutesAgo(180, now),
      decidedAt: minutesAgo(180, now),
      slaDeadlineAt: minutesAgo(179.5, now),
      retryCount: 0,
      operation: "TRANSFER",
      assetId: "BTC",
      amount: "0.75",
      amountUsd: 48_900,
      sourceName: "Treasury Hot",
      sourceId: "0",
      sourceType: "VAULT",
      destName: "Kraken",
      destId: "kraken",
      destType: "EXCHANGE",
      destAddress: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
      destAddressType: "WHITELISTED",
      note: "Kraken inventory",
      fee: "0.00012 BTC",
      signerId: "api_signer_treasury",
      cosignerId: "cosigner-nitro-prod-1",
      matchedRuleId: "auto-whitelist",
      matchedRuleName: "Auto-sign allowlisted destinations under $100k",
      policyVerdict: "APPROVE",
      decisionSource: "policy",
      rawPayload: {},
    },
  ];
}

export interface SimulatePreset {
  id: string;
  label: string;
  description: string;
  kind: SignRequest["kind"];
  payload: Record<string, unknown>;
}

export const SIMULATE_PRESETS: SimulatePreset[] = [
  {
    id: "internal-gas",
    label: "Internal ETH refill",
    description: "2.0 ETH from Treasury Hot to Gas Station — should auto-sign.",
    kind: "tx_sign",
    payload: {
      operation: "TRANSFER",
      assetId: "ETH",
      amountStr: "2.0",
      amountUSD: 6_600,
      sourceType: "VAULT",
      sourceId: "0",
      destType: "VAULT",
      destId: "12",
      destAddress: "0x22b90e1c44aa9011d0ee4c8f12aa90e31b77001a",
      dstAddressType: "WHITELISTED",
      note: "Simulated gas refill",
      fee: "0.0007 ETH",
      signerId: "api_signer_treasury",
      players: ["cosigner-nitro-prod-1"],
    },
  },
  {
    id: "large-cex",
    label: "Large CEX withdrawal",
    description: "400 ETH to Coinbase Prime — held for operator review.",
    kind: "tx_sign",
    payload: {
      operation: "TRANSFER",
      assetId: "ETH",
      amountStr: "400",
      amountUSD: 1_320_000,
      sourceType: "VAULT",
      sourceId: "0",
      destType: "EXCHANGE",
      destId: "coinbase_prime",
      destAddress: "0x4b1c0e8d9a77c3f2e91a0b6d4c8f12aa90e31b77",
      dstAddressType: "WHITELISTED",
      note: "Simulated CEX top-up",
      fee: "0.003 ETH",
      signerId: "api_signer_treasury",
      players: ["cosigner-nitro-prod-1"],
      destinations: [
        {
          dstName: "Coinbase Prime",
          dstId: "coinbase_prime",
          dstType: "EXCHANGE",
          dstAddress: "0x4b1c0e8d9a77c3f2e91a0b6d4c8f12aa90e31b77",
          dstAddressType: "WHITELISTED",
          amountUSD: 1_320_000,
        },
      ],
    },
  },
  {
    id: "ota-block",
    label: "One-time address payout",
    description: "18 ETH to an unknown address — should auto-reject.",
    kind: "tx_sign",
    payload: {
      operation: "TRANSFER",
      assetId: "ETH",
      amountStr: "18",
      amountUSD: 59_400,
      sourceType: "VAULT",
      sourceId: "0",
      destType: "ONE_TIME",
      destAddress: "0xde4dbeef0000000000000000000000000000cafe",
      dstAddressType: "ONE_TIME",
      note: "Simulated unallowlisted payout",
      signerId: "api_signer_treasury",
      players: ["cosigner-nitro-prod-1"],
    },
  },
  {
    id: "uniswap",
    label: "Uniswap contract call",
    description: "exactInputSingle on Uniswap V3 — held as web3.",
    kind: "tx_sign",
    payload: {
      operation: "CONTRACT_CALL",
      assetId: "ETH",
      amountStr: "15",
      amountUSD: 49_500,
      sourceType: "VAULT",
      sourceId: "3",
      destType: "UNMANAGED",
      destId: "uniswap_v3",
      destAddress: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
      dstAddressType: "WHITELISTED",
      note: "Simulated Uniswap swap",
      signerId: "api_signer_treasury",
      players: ["cosigner-nitro-prod-1"],
      destinations: [
        {
          dstName: "Uniswap V3 Router",
          dstId: "uniswap_v3",
          dstType: "UNMANAGED",
          dstAddress: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
          dstAddressType: "WHITELISTED",
          amountUSD: 49_500,
        },
      ],
    },
  },
  {
    id: "policy-edit",
    label: "Policy change approval",
    description: "Raise auto-sign ceiling — held as a config change.",
    kind: "config_change",
    payload: {
      type: "POLICY_APPROVAL",
      extraInfo: {
        summary: "Raise Kraken auto-sign ceiling from $100k to $150k",
        submittedBy: "treasury-lead@northstar",
        ...whitelistProposal(150_000),
      },
      signerId: "api_approver_ops",
      players: ["cosigner-sgx-dr-1"],
    },
  },
];

export function seedAudit(requests: SignRequest[], now: number) {
  const events = [];
  for (const request of requests) {
    events.push({
      id: `aud_${request.id}_in`,
      at: request.createdAt,
      requestId: request.id,
      action: "CALLBACK_RECEIVED",
      actor: request.cosignerId,
      detail: `${request.kind} from ${request.cosignerId}`,
    });
    if (request.status === "auto_approved") {
      events.push({
        id: `aud_${request.id}_out`,
        at: request.decidedAt ?? request.createdAt,
        requestId: request.id,
        action: "APPROVE",
        actor: `policy:${request.matchedRuleId}`,
        detail: `Auto-signed by ${request.matchedRuleName}`,
      });
    } else if (request.status === "auto_rejected") {
      events.push({
        id: `aud_${request.id}_out`,
        at: request.decidedAt ?? request.createdAt,
        requestId: request.id,
        action: "REJECT",
        actor: `policy:${request.matchedRuleId}`,
        detail: request.rejectionReason ?? "Auto-rejected by policy",
      });
    } else if (request.status === "approved") {
      events.push({
        id: `aud_${request.id}_out`,
        at: request.decidedAt ?? minutesAgo(1, now),
        requestId: request.id,
        action: "APPROVE",
        actor: request.operator ?? "ops@northstar",
        detail: "Operator co-signed after policy hold",
      });
    }
  }
  return events.sort((a, b) => (a.at < b.at ? 1 : -1));
}
